import type {FishType, GameConfig} from '../types';

const ultraLegendary: FishType[] = [
    {name: '초빙룡 티라노사우루스', chance: 0.0001, price: 1000, length: 300, type: 'dino', rate: 'ultra-legendary'},
    {name: '극한 포식자 스피노사우루스', chance: 0.0001, price: 1200, length: 300, type: 'dino', rate: 'ultra-legendary'},
    {name: '얼어붙은 브라키오사우루스', chance: 0.0001, price: 1500, length: 300, type: 'dino', rate: 'ultra-legendary'},
    {name: '설원의 알로사우루스', chance: 0.0001, price: 1100, length: 400, type: 'dino', rate: 'ultra-legendary'},
    {name: '북극의 벨로키랍토르', chance: 0.0001, price: 1050, length: 300, type: 'dino', rate: 'ultra-legendary'},
    {name: '유빙 트리케라톱스', chance: 0.0001, price: 1300, length: 600, type: 'dino', rate: 'ultra-legendary'},
    {name: '고대 만년설 파키케팔로사우루스', chance: 0.0001, length: 300, price: 1400, type: 'dino', rate: 'ultra-legendary'},
];

const trashs: FishType[] = [
    {name: '낚시 바늘', chance: 0.01, price: -20, length: 5, type: 'trash'},
    {name: '플라스틱 병', chance: 0.02, price: -50, length: 60, type: 'trash'},
    {name: '낡은 타이어', chance: 0.02, price: -60, length: 80, type: 'trash'},
    {name: '신발', chance: 0.03, price: -40, length: 20, type: 'trash'},
    {name: '그물 조각', chance: 0.01, price: -30, length: 500, type: 'trash'},
    {name: '찢어진 부표', chance: 0.02, price: -25, length: 100, type: 'trash'},
    {name: '쓰레기 봉투', chance: 0.01, price: -10, length: 100, type: 'trash'},
    {name: '깨진 병', chance: 0.02, price: -45, length: 60, type: 'trash'},
    {name: '헌 종이', chance: 0.02, price: -15, length: 10, type: 'trash'},
    {name: '낡은 나무 조각', chance: 0.01, price: -50, length: 60, type: 'trash'},
    {name: '비닐 봉투', chance: 0.03, price: -10, length: 20, type: 'trash'},
    {name: '녹슨 캔', chance: 0.02, price: -35, length: 10, type: 'trash'},
    {name: '담배 꽁초', chance: 0.02, price: -10, length: 4, type: 'trash'},
    {name: '헌 장화', chance: 0.01, price: -50, length: 12, type: 'trash'},
    {name: '버려진 낚시줄', chance: 0.02, price: -15, length: 60, type: 'trash'},
    {name: '썩은 조개 껍질', chance: 0.03, price: -80, length: 60, type: 'trash'},
    {name: '갈라진 구슬', chance: 0.01, price: -20, length: 1, type: 'trash'},
    {name: '흙 묻은 장갑', chance: 0.02, price: -50, length: 20, type: 'trash'},
    {name: '망가진 우산', chance: 0.03, price: -50, length: 60, type: 'trash'},
    {name: '버려진 디스코드 서버', chance: 0.03, price: -50, length: 0, type: 'trash'},
    {name: '찢어진 책', chance: 0.01, price: -12, length: 10, type: 'trash'},
    {name: '종이컵', chance: 0.02, price: -50, length: 20, type: 'trash'},
    {name: '헌 모자', chance: 0.02, price: -80, length: 20, type: 'trash'},
    {name: '깨진 유리 조각', chance: 0.02, price: -400, length: 20, type: 'trash'},
    {name: '녹슨 핀', chance: 0.02, price: -20, length: 3, type: 'trash'},
    {name: '해초 덩어리', chance: 0.02, price: -30, length: 20, type: 'trash'},
    {name: '폐지', chance: 0.01, price: -50, length: 20, type: 'trash'},
    {name: '구겨진 플라스틱', chance: 0.03, length: 20, price: -60, type: 'trash'},
    {name: '녹슨 고리', chance: 0.02, price: -80, length: 20, type: 'trash'},
    {name: '손상된 상자', chance: 0.02, price: -12, length: 20, type: 'trash'},
    {name: '낡은 손수건', chance: 0.01, price: -20, length: 20, type: 'trash'},
    {name: '낡은 열쇠', chance: 0.01, price: -70, length: 20, type: 'trash'},
    {name: '누군가의 시험지', chance: 0.01, price: -20, length: 20, type: 'trash'},
    {name: '파손된 플라스틱 장난감', chance: 0.02, length: 20, price: -20, type: 'trash'},
    {name: '드라운드', chance: 0.02, price: -20, length: 20, type: 'trash'},
    {name: '밀랍칠한 약간 녹슨 깎인 구리 반 블록', length: 20, chance: 0.06, price: -100, type: 'trash'},
];

const foods: FishType[] = [
    {name: '세균', chance: 0.01, goodChance: 0.5, price: 5, length: 20, type: 'food'},
    {name: '봉지에 들어있는 햄버거', chance: 0.03, goodChance: 1, length: 20, price: 600, type: 'food'},
    {name: '녹슨 고리', chance: 0.02, price: -80, length: 20, type: 'trash'},
    {name: '손상된 상자', chance: 0.02, price: -12, length: 20, type: 'trash'},
    {name: '낡은 손수건', chance: 0.01, price: -20, length: 20, type: 'trash'},
    {name: '낡은 열쇠', chance: 0.01, price: -70, length: 20, type: 'trash'},
    {name: '누군가의 시험지', chance: 0.01, price: -20, length: 20, type: 'trash'},
    {name: '파손된 플라스틱 장난감', chance: 0.02, length: 20, price: -20, type: 'trash'},
    {name: '드라운드', chance: 0.02, price: -20, length: 20, type: 'trash'},
    {name: '밀랍칠한 약간 녹슨 깎인 구리 반 블록', length: 20, chance: 0.06, price: -100, type: 'trash'},
];

export const gameConfig: GameConfig = {
    terrains: [
        {
            name: '바다',
            fishTypes: [
                {name: '고등어', chance: 0.5, price: 10, length: 60, rate: 'common'},
                {name: '참치', chance: 0.3, price: 20, length: 60, rate: 'uncommon'},
                {name: '연어', chance: 0.15, price: 30, length: 60, rate: 'rare'},
                {name: '상어', chance: 0.05, price: 50, length: 60, rate: 'epic'},
                {name: '붕장어', chance: 0.08, price: 12, length: 60, rate: 'common'},
                {name: '돗돔', chance: 0.07, price: 45, length: 60, rate: 'rare'},
                {name: '방어', chance: 0.06, price: 30, length: 60, rate: 'uncommon'},
                {name: '전갱이', chance: 0.09, price: 15, length: 60, rate: 'common'},
                {name: '광어', chance: 0.07, price: 25, length: 60, rate: 'common'},
                {name: '감성돔', chance: 0.04, price: 40, length: 60, rate: 'rare'},
                {name: '민어', chance: 0.05, price: 20, length: 60, rate: 'uncommon'},
                {name: '참돔', chance: 0.06, price: 35, length: 60, rate: 'uncommon'},
                {name: '부시리', chance: 0.04, price: 50, length: 60, rate: 'epic'},
                {name: '다금바리', chance: 0.03, price: 55, length: 60, rate: 'epic'},
                {name: '청새치', chance: 0.02, price: 170, length: 60, rate: 'legendary'},
                {name: '문어', chance: 0.02, price: 45, length: 140, rate: 'rare'},
                {name: '해삼', chance: 0.06, price: 80, length: 60, rate: 'common'},
                {name: '멸치', chance: 0.1, price: 50, length: 60, rate: 'common'},
                {name: '장어', chance: 0.05, price: 40, length: 60, rate: 'rare'},
                {name: '낙지', chance: 0.07, price: 35, length: 60, rate: 'uncommon'},
                {name: '상어지느러미', chance: 0.02, price: 600, length: 60, rate: 'legendary'},
                {name: '돌돔', chance: 0.06, price: 27, length: 60, rate: 'uncommon'},
                {name: '게', chance: 0.08, price: 90, length: 60, rate: 'rare'},
                {name: '청어', chance: 0.04, price: 15, length: 50, rate: 'common'},
                {name: '가자미', chance: 0.06, price: 30, length: 50, rate: 'uncommon'},
                {name: '돔', chance: 0.03, price: 45, length: 60, rate: 'rare'},
                {name: '삼치', chance: 0.02, price: 50, length: 70, rate: 'epic'},
                {name: '연어광어', chance: 0.01, price: 80, length: 80, rate: 'legendary'},
                {name: '블루길', chance: 0.04, price: 15, length: 30, rate: 'common'},
                {name: '하늘색 물고기', chance: 0.02, price: 45, length: 60, rate: 'rare'},
                {name: '하모', chance: 0.03, price: 25, length: 50, rate: 'uncommon'},
                {name: '갑오징어', chance: 0.05, price: 50, length: 70, rate: 'common'},
                {name: '장어장', chance: 0.02, price: 30, length: 60, rate: 'rare'},
                {name: '바다코끼리', chance: 0.01, price: 200, length: 1000, rate: 'legendary'},
                {name: '황어', chance: 0.06, price: 10, length: 25, rate: 'common'},
                {name: '해파리', chance: 0.02, price: 15, length: 30, rate: 'common'},
                {name: '노랑망둥어', chance: 0.05, price: 20, length: 50, rate: 'uncommon'},
                {name: '흰다리새우', chance: 0.04, price: 35, length: 15, rate: 'rare'},
                {name: '복어', chance: 0.03, price: 60, length: 40, rate: 'epic'},
                {name: '물메기', chance: 0.04, price: 25, length: 50, rate: 'uncommon'},
                {name: '갯지렁이', chance: 0.06, price: 10, length: 5, rate: 'common'},
                {name: '다람쥐물고기', chance: 0.01, price: 100, length: 20, rate: 'legendary'},
                {name: '아귀', chance: 0.03, price: 40, length: 70, rate: 'rare'},
                {name: '로브스터', chance: 0.02, price: 150, length: 30, rate: 'epic'},
                {name: '성게', chance: 0.05, price: 20, length: 15, rate: 'common'},
                {name: '흑임자', chance: 0.04, price: 45, length: 60, rate: 'uncommon'},
                {name: '금붕어', chance: 0.02, price: 90, length: 10, rate: 'rare'},
                {name: '해수어', chance: 0.01, price: 80, length: 50, rate: 'legendary'},
                {name: '방울새우', chance: 0.03, price: 25, length: 8, rate: 'uncommon'},
                {name: '미꾸라지', chance: 0.06, price: 10, length: 30, rate: 'common'},
                {name: '붉은바닥물고기', chance: 0.02, price: 70, length: 40, rate: 'rare'},
                {name: '황새치', chance: 0.04, price: 55, length: 100, rate: 'epic'},
                {name: '문어발', chance: 0.03, price: 25, length: 20, rate: 'uncommon'},
                {name: '대게', chance: 0.01, price: 250, length: 60, rate: 'legendary'},
                {name: '피라냐', chance: 0.02, price: 60, length: 50, rate: 'uncommon'},
                {name: '로켓물고기', chance: 0.03, price: 40, length: 30, rate: 'common'},
                {name: '황금붕어', chance: 0.01, price: 100, length: 15, rate: 'legendary'},
                {name: '쏨뱅이', chance: 0.05, price: 20, length: 20, rate: 'common'},
                {name: '리얼로보', chance: 0.02, price: 55, length: 50, rate: 'rare'},
                {name: '투구새우', chance: 0.04, price: 30, length: 40, rate: 'uncommon'},
                {name: '가자미', chance: 0.05, price: 25, length: 50, rate: 'common'},
                {name: '왕새우', chance: 0.03, price: 80, length: 25, rate: 'epic'},
                {name: '뱀장어', chance: 0.02, price: 70, length: 60, rate: 'rare'},
                {name: '독가시고기', chance: 0.01, price: 200, length: 45, rate: 'legendary'},
                {name: '아카시아물고기', chance: 0.03, price: 35, length: 35, rate: 'uncommon'},
                {name: '토끼상어', chance: 0.02, price: 90, length: 75, rate: 'rare'},
                {name: '백상아리', chance: 0.01, price: 500, length: 300, rate: 'legendary'},
                {name: '명태', chance: 0.04, price: 40, length: 80, rate: 'common'},
                {name: '해마', chance: 0.06, price: 20, length: 10, rate: 'uncommon'},
                {name: '노란해파리', chance: 0.05, price: 15, length: 30, rate: 'common'},
                {name: '붉은코끼리물고기', chance: 0.02, price: 100, length: 50, rate: 'legendary'},
                {name: '하늘색 상어', chance: 0.03, price: 60, length: 70, rate: 'epic'},
                {name: '구리붕어', chance: 0.02, price: 45, length: 20, rate: 'rare'},
                {name: '줄무늬고등어', chance: 0.04, price: 30, length: 60, rate: 'common'},
                {name: '검정물고기', chance: 0.01, price: 120, length: 50, rate: 'legendary'},
                {name: '황금상어', chance: 0.01, price: 400, length: 200, rate: 'legendary'},
                {name: '오징어', chance: 0.04, price: 35, length: 45, rate: 'uncommon'},
                {name: '은상어', chance: 0.02, price: 75, length: 90, rate: 'epic'},
                {name: '파란 바다거북이', chance: 0.02, price: 150, length: 80, rate: 'rare'},
                {name: '물고기왕', chance: 0.01, price: 300, length: 150, rate: 'legendary'},
                {name: '붉은 대게', chance: 0.03, price: 40, length: 60, rate: 'uncommon'},
                {name: '철갑상어', chance: 0.02, price: 200, length: 120, rate: 'epic'},
                {name: '말미잘', chance: 0.04, price: 25, length: 10, rate: 'common'},
                {name: '진주조개', chance: 0.01, price: 250, length: 5, rate: 'legendary'},
                {name: '복어', chance: 0.02, price: 90, length: 40, rate: 'rare'},
                {name: '오로라 물고기', chance: 0.03, price: 50, length: 30, rate: 'uncommon'},
                {name: '고래상어', chance: 0.01, price: 600, length: 400, rate: 'legendary'},
                ...trashs,
                ...ultraLegendary,
            ],
        },
        {
            name: '쓰레기장',
            fishTypes: [...trashs, ...ultraLegendary],
        },
        {
            name: '강',
            fishTypes: [
                {name: '고철', chance: 0.1, price: -140, length: 100, type: 'trash'},
                {name: '이상한 나라의 엘... 아니 물고기', chance: 0.08, price: 80, length: 60},
                {name: '쏘가리', chance: 0.05, price: 35, length: 60},
                {name: '메기', chance: 0.05, price: 20, length: 70, rate: 'common'},
                {name: '농어', chance: 0.02, price: 35, length: 50, rate: 'rare'},
                {name: '볼락', chance: 0.03, price: 25, length: 40, rate: 'common'},
                {name: '진주조개', chance: 0.05, price: 90, length: 30, rate: 'uncommon'},
                {name: '두부고기', chance: 0.02, price: 25, length: 50, rate: 'uncommon'},
                {name: '금붕어', chance: 0.06, price: 12, length: 20, rate: 'common'},
                {name: '낙지볶음', chance: 0.05, price: 10, length: 25, type: 'trash'},
                {name: '잉어', chance: 0.05, price: 10, rate: 'common'},
                {name: '붕어', chance: 0.05, price: 80, rate: 'common'},
                {name: '메기', chance: 0.04, price: 20, rate: 'uncommon'},
                {name: '금붕어', chance: 0.02, price: 50, rate: 'rare'},
                {name: '가물치', chance: 0.01, price: 60, rate: 'epic'},
                {name: '송어', chance: 0.02, price: 30, rate: 'rare'},
                {name: '황어', chance: 0.03, price: 15, rate: 'common'},
                {name: '꺽지', chance: 0.03, price: 12, rate: 'common'},
                {name: '은어', chance: 0.02, price: 25, rate: 'uncommon'},
                {name: '민물 장어', chance: 0.01, price: 55, rate: 'epic'},
                {name: '강꼬치고기', chance: 0.02, price: 30, rate: 'uncommon'},
                {name: '쏘가리', chance: 0.02, price: 35, rate: 'rare'},
                {name: '참게', chance: 0.04, price: 10, rate: 'common'},
                {name: '모래무지', chance: 0.03, price: 70, rate: 'common'},
                {name: '검정피라미', chance: 0.03, price: 12, rate: 'common'},
                {name: '새우', chance: 0.05, price: 50, rate: 'common'},
                {name: '황금 잉어', chance: 0.01, price: 80, rate: 'legendary'},
                {name: '연어', chance: 0.02, price: 35, rate: 'uncommon'},
                {name: '산천어', chance: 0.02, price: 28, rate: 'rare'},
                {name: '무태장어', chance: 0.01, price: 70, rate: 'epic'},
                {name: '강준치', chance: 0.03, price: 18, rate: 'common'},
                {name: '대농갱이', chance: 0.02, price: 15, rate: 'common'},
                {name: '피라미', chance: 0.04, price: 60, rate: 'common'},
                {name: '돌고기', chance: 0.03, price: 10, rate: 'common'},
                {name: '큰입배스', chance: 0.02, price: 40, rate: 'rare'},
                {name: '블루길', chance: 0.03, price: 12, rate: 'common'},
                {name: '고동', chance: 0.05, price: 40, rate: 'common'},
                {name: '잉어알', chance: 0.04, price: 20, rate: 'uncommon'},
                {name: '가재', chance: 0.04, price: 80, rate: 'common'},
                {name: '도롱뇽', chance: 0.02, price: 15, rate: 'common'},
                {name: '민물새우', chance: 0.05, price: 50, rate: 'common'},
                {name: '은잉어', chance: 0.01, price: 65, rate: 'epic'},
                {name: '황소치어', chance: 0.03, price: 10, rate: 'common'},
                {name: '강도래', chance: 0.05, price: 40, type: 'trash'},
                {name: '방개', chance: 0.03, price: 10, rate: 'common'},
                {name: '구피', chance: 0.02, price: 25, rate: 'uncommon'},
                {name: '뱀장어', chance: 0.01, price: 120, rate: 'epic'},
                {name: '돌돔', chance: 0.02, price: 100, rate: 'rare'},
                {name: '미꾸라지', chance: 0.04, price: 70, rate: 'common'},
                {name: '도마뱀', chance: 0.02, price: 15, rate: 'common'},
                {name: '황금새우', chance: 0.01, price: 875, rate: 'legendary'},
                {name: '가재왕', chance: 0.02, price: 45, rate: 'rare'},
                {name: '방어', chance: 0.02, price: 20, rate: 'uncommon'},
                {name: '돌말', chance: 0.03, price: -10, type: 'trash'},
                {name: '송사리', chance: 0.04, price: 80, rate: 'common'},
                {name: '민물고동', chance: 0.04, price: 50, rate: 'common'},
                {name: '게거미', chance: 0.01, price: 120, rate: 'legendary'},
                {name: '잉어 왕', chance: 0.01, price: 570, rate: 'legendary'},
                ...trashs,
                ...ultraLegendary,
            ],
        },
        {
            name: '디스코드',
            fishTypes: [
                {name: '버려진 서버', chance: 0.08, price: -10, type: 'trash', rate: 'common'},
                {name: '디스코드 공식 서버', chance: 0.01, price: 100, type: 'fish', rate: 'legendary'},
                {name: '채팅 로그', chance: 0.06, price: -50, type: 'trash', rate: 'common'},
                {name: '프로필 사진', chance: 0.03, price: 20, type: 'trash', rate: 'uncommon'},
                {name: '버그 리포트', chance: 0.04, price: 30, type: 'trash', rate: 'uncommon'},
                {name: '초대 링크', chance: 0.04, price: 10, type: 'trash', rate: 'common'},
                {name: '디스코드 티셔츠', chance: 0.02, price: 150, type: 'trash', rate: 'rare'},
                {name: '메시지 남기기', chance: 0.03, price: -20, type: 'trash', rate: 'common'},
                {name: '낡은 서버 인증서', chance: 0.02, price: 100, type: 'trash', rate: 'uncommon'},
                {name: '봇 초대 토큰', chance: 0.03, price: 50, type: 'trash', rate: 'uncommon'},
                {name: '밴 로그', chance: 0.01, price: -150, type: 'trash', rate: 'epic'},
                {name: '캔슬된 Nitro', chance: 0.02, price: -70, type: 'trash', rate: 'rare'},
                {name: '서버 아바타', chance: 0.05, price: 40, type: 'trash', rate: 'common'},
                {name: '비공개 채널 링크', chance: 0.02, price: 200, type: 'trash', rate: 'rare'},
                {name: '서버 부스트 잔재', chance: 0.04, price: 80, type: 'trash', rate: 'uncommon'},
                {name: '친구 요청', chance: 0.03, price: 20, type: 'trash', rate: 'common'},
                {name: '밴 권한', chance: 0.01, price: -200, type: 'trash', rate: 'epic'},
                {name: '디스코드 이모티콘', chance: 0.03, price: 10, type: 'trash', rate: 'common'},
                {name: '채널 핀', chance: 0.02, price: 30, type: 'trash', rate: 'uncommon'},
            ],
        },
        {
            name: '북극',
            fishTypes: [
                {name: '흰동가리', chance: 0.05, price: 20, type: 'fish', rate: 'common'},
                {name: '빙어', chance: 0.1, price: 30, type: 'fish', rate: 'uncommon'},
                {name: '북극 장어', chance: 0.03, price: 50, type: 'fish', rate: 'rare'},
                {name: '바다표범', chance: 0.02, price: 80, type: 'fish', rate: 'epic'},
                {name: '백사자', chance: 0.01, price: 400, type: 'fish', rate: 'legendary'},
                {name: '얼음 생선', chance: 0.06, price: 10, type: 'fish', rate: 'common'},
                {name: '북극 고래', chance: 0.02, price: 120, type: 'fish', rate: 'epic'},
                {name: '물개', chance: 0.03, price: 40, type: 'fish', rate: 'uncommon'},
                {name: '그린란드 상어', chance: 0.015, price: 450, type: 'fish', rate: 'epic'},
                {name: '북극곰', chance: 0.02, price: 410, type: 'fish', rate: 'epic'},
                {name: '얼음갈치', chance: 0.04, price: 60, type: 'fish', rate: 'rare'},
                {name: '대서양 대구', chance: 0.03, price: 90, type: 'fish', rate: 'uncommon'},
                {name: '고대 수룡', chance: 0.01, price: 800, type: 'fish', rate: 'legendary'},
                {name: '빙산 조각', chance: 0.06, price: -5, type: 'trash', rate: 'common'},
                {name: '쓰레기 봉투', chance: 0.04, price: -10, type: 'trash', rate: 'common'},
                {name: '녹슨 쇠막대기', chance: 0.03, price: -7, type: 'trash', rate: 'uncommon'},
                {name: '겨울 옷', chance: 0.02, price: -15, type: 'trash', rate: 'rare'},
                {name: '버려진 스노모바일', chance: 0.01, price: -20, type: 'trash', rate: 'epic'},
                {name: '얼음조각', chance: 0.06, price: -1, type: 'trash', rate: 'common'},
                {name: '파손된 어망', chance: 0.04, price: -3, type: 'trash', rate: 'common'},
                {name: '깨진 유리', chance: 0.03, price: -5, type: 'trash', rate: 'uncommon'},
                {name: '손상된 카메라', chance: 0.02, price: -8, type: 'trash', rate: 'rare'},
                {name: '스키', chance: 0.03, price: -4, type: 'trash', rate: 'uncommon'},
                {name: '조각난 얼음판', chance: 0.05, price: -1, type: 'trash', rate: 'common'},
                ...trashs,
                ...ultraLegendary,
            ],
        },
        {
            name: '정글',
            fishTypes: [
                {name: '열대어', chance: 0.027, price: 20, type: 'fish', rate: 'common'},
                {name: '열대 식물', chance: 0.081, price: 50, type: 'fish', rate: 'common'},
                {name: '야자수 잎', chance: 0.063, price: 50, type: 'fish', rate: 'uncommon'},
                {name: '초록색 도마뱀', chance: 0.038, price: 70, type: 'fish', rate: 'rare'},
                {name: '바나나 나무 잎', chance: 0.081, price: 40, type: 'fish', rate: 'common'},
                {name: '갈색 나비', chance: 0.063, price: 30, type: 'fish', rate: 'uncommon'},
                {name: '잎사귀', chance: 0.081, price: 10, type: 'fish', rate: 'common'},
                {name: '정글 곤충', chance: 0.05, price: 40, type: 'fish', rate: 'uncommon'},
                {name: '작은 거미', chance: 0.081, price: 10, type: 'fish', rate: 'common'},
                {name: '개구리알', chance: 0.038, price: 40, type: 'fish', rate: 'rare'},
                {name: '덩굴 식물', chance: 0.05, price: 50, type: 'fish', rate: 'uncommon'},
                {name: '열대 과일', chance: 0.05, price: 60, type: 'fish', rate: 'common'},
                {name: '노란색 개미', chance: 0.063, price: 20, type: 'fish', rate: 'uncommon'},
                {name: '작은 파충류', chance: 0.027, price: 80, type: 'fish', rate: 'rare'},
                {name: '큰 나뭇잎', chance: 0.081, price: 30, type: 'fish', rate: 'common'},
                {name: '정글 나무껍질', chance: 0.05, price: 10, type: 'fish', rate: 'common'},
                {name: '열대 버섯', chance: 0.038, price: 70, type: 'fish', rate: 'rare'},
                {name: '정글 독버섯', chance: 0.013, price: -120, type: 'trash', rate: 'legendary'},
                {name: '작은 벌', chance: 0.05, price: -10, type: 'trash', rate: 'common'},
                {name: '비단벌레', chance: 0.05, price: 20, type: 'fish', rate: 'common'},
                {name: '정글 호랑나비', chance: 0.038, price: 50, type: 'fish', rate: 'uncommon'},
                {name: '망고 나무 잎', chance: 0.05, price: 40, type: 'fish', rate: 'uncommon'},
                {name: '작은 개구리', chance: 0.027, price: 80, type: 'fish', rate: 'rare'},
                {name: '작은 방아벌레', chance: 0.027, price: 30, type: 'fish', rate: 'common'},
                {name: '열대 나비', chance: 0.038, price: 50, type: 'fish', rate: 'uncommon'},
                {name: '정글 대벌레', chance: 0.038, price: 40, type: 'fish', rate: 'rare'},
                {name: '짜투리 식물', chance: 0.05, price: -30, type: 'trash', rate: 'common'},
                {name: '얇은 열매', chance: 0.038, price: 30, type: 'fish', rate: 'uncommon'},
                {name: '정글 소금쟁이', chance: 0.027, price: 30, type: 'fish', rate: 'rare'},
                {name: '정글 식충식물', chance: 0.013, price: 100, type: 'fish', rate: 'legendary'},
                {name: '흰색 나비', chance: 0.038, price: 30, type: 'fish', rate: 'uncommon'},
                {name: '열대 새', chance: 0.027, price: 90, type: 'fish', rate: 'rare'},
                {name: '정글 방아벌레', chance: 0.027, price: 20, type: 'fish', rate: 'uncommon'},
                {name: '서양솜털버섯', chance: 0.05, price: 60, type: 'fish', rate: 'common'},
                {name: '정글 뿌리', chance: 0.081, price: 40, type: 'fish', rate: 'common'},
                {name: '작은 열대 새', chance: 0.027, price: 80, type: 'fish', rate: 'rare'},
                {name: '황금 색 난초', chance: 0.013, price: 150, type: 'fish', rate: 'legendary'},
                {name: '열대 소나무 잎', chance: 0.05, price: 40, type: 'fish', rate: 'uncommon'},
                {name: '작은 거미줄', chance: 0.063, price: 20, type: 'fish', rate: 'common'},
                {name: '열대 황금버섯', chance: 0.013, price: 100, type: 'fish', rate: 'legendary'},
                {name: '미끄러운 돌', chance: 0.027, price: -50, type: 'trash', rate: 'uncommon'},
                {name: '정글 개구리', chance: 0.038, price: 40, type: 'fish', rate: 'rare'},
                {name: '정글 대왕벌', chance: 0.027, price: 60, type: 'fish', rate: 'uncommon'},
                {name: '정글 고양이', chance: 0.038, price: 50, type: 'fish', rate: 'rare'},
                {name: '정글 도마뱀', chance: 0.027, price: 70, type: 'fish', rate: 'uncommon'},
                {name: '열대 나무', chance: 0.05, price: 40, type: 'fish', rate: 'common'},
                {name: '검은색 방울벌레', chance: 0.038, price: 30, type: 'fish', rate: 'uncommon'},
                {name: '정글 덩굴식물', chance: 0.05, price: 20, type: 'fish', rate: 'common'},
                {name: '정글 흰꽃', chance: 0.027, price: 40, type: 'fish', rate: 'rare'},
                {name: '정글 여치', chance: 0.05, price: 20, type: 'fish', rate: 'common'},
                {name: '정글 나무껍질', chance: 0.05, price: 10, type: 'fish', rate: 'common'},
                {name: '열대 꽃가루', chance: 0.05, price: 20, type: 'fish', rate: 'common'},
                {name: '정글 버섯', chance: 0.027, price: 50, type: 'fish', rate: 'uncommon'},
                {name: '작은 열대 나무', chance: 0.027, price: 80, type: 'fish', rate: 'rare'},
                {name: '정글 광대버섯', chance: 0.013, price: -150, type: 'trash', rate: 'legendary'},
                {name: '작은 나뭇잎', chance: 0.081, price: 10, type: 'fish', rate: 'common'},
                {name: '정글 개미집', chance: 0.027, price: 30, type: 'fish', rate: 'rare'},
                ...trashs,
                ...ultraLegendary,
            ],
        },
        {
            name: '숲',
            fishTypes: [
                {name: '산새', chance: 0.06, price: 150, type: 'fish', rate: 'common'},
                {name: '버섯', chance: 0.05, price: 20, type: 'trash', rate: 'common'},
                {name: '이끼', chance: 0.04, price: 10, type: 'trash', rate: 'common'},
                {name: '청설모', chance: 0.03, price: 70, type: 'trash', rate: 'uncommon'},
                {name: '조류 깃털', chance: 0.05, price: 30, type: 'trash', rate: 'uncommon'},
                {name: '버려진 둥지', chance: 0.02, price: 80, type: 'trash', rate: 'rare'},
                {name: '고슴도치', chance: 0.01, price: 100, type: 'trash', rate: 'epic'},
                {name: '산호', chance: 0.03, price: 120, type: 'fish', rate: 'rare'},
                {name: '숲의 벌레', chance: 0.04, price: 10, type: 'trash', rate: 'common'},
                ...trashs,
                ...ultraLegendary,
            ],
        },
    ],
    fishWaitTime: {min: 2000, max: 5000},
    fishBiteTime: {min: 2000, max: 3000},
    fishEscapeChance: 0.3,
    minCatchTime: 1000,
    priceVariation: 0.7,
};
